#! /bin/zsh

BATTERY=$(acpi -b | cut -d',' -f2 | grep -o '[[:alnum:]]*')
CHARGER=$(acpi -a | cut -d' ' -f3)

case $BATTERY in
	[8-9]?|100)
		LEVEL="\uf240"
		;;
	[6-7]?)
		LEVEL="\uf241"
		;;
	[4-5]?)
		LEVEL="\uf242"
		;;
	[2-3]?)
		LEVEL="\uf243"
		;;
	1?)
		LEVEL="\uf244"
		;;
	[0-9])
		LEVEL="%{F#FFA54242}\uf244%{F-}"
		;;
	*)
		LEVEL="%{F#FFA54242}\uf071%{F-}"
		;;
esac

if [[ $CHARGER = "on-line" ]] ; then
	BOLT="%{T3} \uf0e7%{T-}"
else
	BOLT="%{F#FF707880}%{T3} \uf0e7%{T-}%{F-}"
fi

echo "B$LEVEL$BOLT"

if [[ $BATTERY -le 15 && ! $CHARGER = "on-line" ]] ; then
	export BATTERY
	~/dotfiles/sysscripts/battwarn.sh &
elif [[ $BATTERY -le 15 && $CHARGER = "on-line" ]] ; then
	echo "150" > /tmp/battwarn
else
	echo "0" > /tmp/battwarn
fi
