#! /bin/zsh

pactl info | grep -F -e "Default Sink: alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.stereo-game" && ICON="uf025" || ICON="uf028"

VOL=$(pactl get-sink-volume @DEFAULT_SINK@ | cut -sd "/" -f 2 | grep -o '[[:alnum:]]*')
MUTE=$(pactl get-sink-mute @DEFAULT_SINK@ | cut -d " " -f 2)

if [[ $MUTE == "yes" ]] ; then
	VOL="%{F#FF707880}\\${ICON} $VOL%"
else
	VOL="\\${ICON} $VOL%"
fi

echo "V$VOL"
